//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::account::Entity as Account;
pub use super::permission::Entity as Permission;
pub use super::role::Entity as Role;
pub use super::role_permission::Entity as RolePermission;
pub use super::user::Entity as User;
