//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "type")]
pub enum Type {
    #[sea_orm(string_value = "none")]
    None,
    #[sea_orm(string_value = "google")]
    Google,
    #[sea_orm(string_value = "tiktok")]
    Tiktok,
}
