//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub public_id: Uuid,
    pub user_name: String,
    pub email: String,
    pub role_id: i32,
    pub date_of_birth: DateTime,
    pub gender: bool,
    pub avatar: String,
    pub phone_number: String,
    #[sea_orm(column_type = "Text")]
    pub text_search: String,
    pub created_at: DateTime,
    pub created_by: i32,
    pub updated_at: DateTime,
    pub updated_by: i32,
    pub is_deleted: bool,
    pub deleted_at: DateTime,
    pub deleted_by: i32,
    pub is_actived: bool,
    pub actived_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account::Entity")]
    Account,
    #[sea_orm(
        belongs_to = "super::role::Entity",
        from = "Column::RoleId",
        to = "super::role::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Role,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Role.def()
    }
}


pub  struct UserToPermission;

impl Linked for UserToPermission  {
    type FromEntity=super::user::Entity;

    type ToEntity=super::permission::Entity;

    fn link(&self) -> Vec<sea_orm::LinkDef> {
        vec![
            super::user::Relation::Role.def(),
            super::role::Relation::RolePermission.def().rev(),
            super::role_permission::Relation::Permission.def()
        ]
    }
}

impl ActiveModelBehavior for ActiveModel {}
